# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_location_postal'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio_visibility',
            field=models.CharField(blank=True, choices=[('everyone', 'Everyone'), ('connections', 'Connections only'), ('only_me', 'Only me')], default='everyone', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='family_visibility',
            field=models.CharField(blank=True, choices=[('everyone', 'Everyone'), ('connections', 'Connections only'), ('only_me', 'Only me')], default='everyone', max_length=20, null=True),
        ),
    ]
