# Generated by Django 5.2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def set_existing_users_approved(apps, schema_editor):
    CustomUser = apps.get_model('accounts', 'CustomUser')
    CustomUser.objects.all().update(approval_status='approved')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_family_visibility_bio_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='approval_status',
            field=models.CharField(
                choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected')],
                default='pending',
                help_text='User can log in when pending but only sees waitlist status until approved.',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='customuser',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='newsletter_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='approved_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='approved_users',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(set_existing_users_approved, migrations.RunPython.noop),
    ]
