# Generated by Django 5.2 on 2026-02-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_community_investmentprofile_jobposting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentprofile',
            name='check_size_range',
            field=models.CharField(choices=[('1000-5000', '1000-5000'), ('5000-10000', '5000-10000'), ('10000-20000', '10000-20000'), ('20000-50000', '20000-50000'), ('50000-100000', '50000-100000'), ('100000+', '100000+')], default='1000-5000', max_length=50),
        ),
        migrations.AddField(
            model_name='investmentprofile',
            name='facebook',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investmentprofile',
            name='instagram',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investmentprofile',
            name='linkedin',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investmentprofile',
            name='philosophy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmentprofile',
            name='twitter',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
