# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_investmentprofile_check_size_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
