# Generated by Django 5.2
# Phase 7: Creators/Influencers & Micro-Investors

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_event_eventregistration_eventreminder_eventparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentprofile',
            name='is_micro_investor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investmentprofile',
            name='is_creator_influencer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investmentprofile',
            name='audience_reach',
            field=models.CharField(blank=True, help_text='e.g. "10K LinkedIn", "50K YouTube"', max_length=255, null=True),
        ),
    ]
